# 2do: setup anitiaffinity on release 1.4: https://github.com/kubernetes/kubernetes/blob/release-1.4/docs/design/podaffinity.md
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: micro-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: microservice
        name: test
    spec:
      containers:
      - name: service
        image: us.gcr.io/spair-api/hello
        ports:
        - containerPort: 8080
          name: transport
          protocol: TCP
        - containerPort: 8081
          name: healthcheck
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /_ah/health
            port: 8081
          initialDelaySeconds: 10
          timeoutSeconds: 1
        # lifecycle:
        #   postStart:
        #     exec:
        #       command:
        #         - some
        #         - items
        #   preStop:
        #     exec:
        #       command:
        #         - some
        #         - items
        command:
          - npm
          - start
